# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from .pipeline_stage import PipelineStage

__all__ = ["Pipeline"]


class Pipeline(BaseModel):
    id: str
    """
    A unique identifier generated by HubSpot that can be used to retrieve and update
    the pipeline.
    """

    archived: bool
    """Whether the pipeline is archived."""

    created_at: datetime = FieldInfo(alias="createdAt")
    """The date the pipeline was created.

    The default pipelines will have createdAt = 0.
    """

    display_order: int = FieldInfo(alias="displayOrder")
    """The order for displaying this pipeline.

    If two pipelines have a matching `displayOrder`, they will be sorted
    alphabetically by label.
    """

    label: str
    """A unique label used to organize pipelines in HubSpot's UI"""

    stages: List[PipelineStage]
    """The stages associated with the pipeline.

    They can be retrieved and updated via the pipeline stages endpoints.
    """

    updated_at: datetime = FieldInfo(alias="updatedAt")
    """The date the pipeline was last updated."""

    archived_at: Optional[datetime] = FieldInfo(alias="archivedAt", default=None)
    """The date the pipeline was archived.

    `archivedAt` will only be present if the pipeline is archived.
    """
