# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .external_option import ExternalOption as ExternalOption
from .external_time_range import ExternalTimeRange as ExternalTimeRange
from .external_booking_info import ExternalBookingInfo as ExternalBookingInfo
from .external_closed_range import ExternalClosedRange as ExternalClosedRange
from .external_user_profile import ExternalUserProfile as ExternalUserProfile
from .external_link_metadata import ExternalLinkMetadata as ExternalLinkMetadata
from .external_meetings_user import ExternalMeetingsUser as ExternalMeetingsUser
from .external_guest_settings import ExternalGuestSettings as ExternalGuestSettings
from .external_reminder_param import ExternalReminderParam as ExternalReminderParam
from .external_link_form_field import ExternalLinkFormField as ExternalLinkFormField
from .external_user_busy_times import ExternalUserBusyTimes as ExternalUserBusyTimes
from .external_branding_metadata import ExternalBrandingMetadata as ExternalBrandingMetadata
from .external_link_availability import ExternalLinkAvailability as ExternalLinkAvailability
from .external_link_display_info import ExternalLinkDisplayInfo as ExternalLinkDisplayInfo
from .external_meeting_availability import ExternalMeetingAvailability as ExternalMeetingAvailability
from .external_validated_form_field import ExternalValidatedFormField as ExternalValidatedFormField
from .external_legal_consent_options import ExternalLegalConsentOptions as ExternalLegalConsentOptions
from .external_legal_consent_response import ExternalLegalConsentResponse as ExternalLegalConsentResponse
from .external_meetings_link_settings import ExternalMeetingsLinkSettings as ExternalMeetingsLinkSettings
from .external_booking_form_field_param import ExternalBookingFormFieldParam as ExternalBookingFormFieldParam
from .external_meeting_booking_response import ExternalMeetingBookingResponse as ExternalMeetingBookingResponse
from .external_legal_consent_response_param import (
    ExternalLegalConsentResponseParam as ExternalLegalConsentResponseParam,
)
from .external_meetings_welcome_screen_info import (
    ExternalMeetingsWelcomeScreenInfo as ExternalMeetingsWelcomeScreenInfo,
)
from .external_email_reminder_schedule_param import (
    ExternalEmailReminderScheduleParam as ExternalEmailReminderScheduleParam,
)
from .external_communication_consent_checkbox import (
    ExternalCommunicationConsentCheckbox as ExternalCommunicationConsentCheckbox,
)
from .external_link_availability_for_duration import (
    ExternalLinkAvailabilityForDuration as ExternalLinkAvailabilityForDuration,
)
from .external_calender_meeting_event_response import (
    ExternalCalenderMeetingEventResponse as ExternalCalenderMeetingEventResponse,
)
from .external_association_create_request_param import (
    ExternalAssociationCreateRequestParam as ExternalAssociationCreateRequestParam,
)
from .external_link_availability_and_busy_times import (
    ExternalLinkAvailabilityAndBusyTimes as ExternalLinkAvailabilityAndBusyTimes,
)
from .external_calendar_meeting_event_response_properties import (
    ExternalCalendarMeetingEventResponseProperties as ExternalCalendarMeetingEventResponseProperties,
)
from .external_calendar_meeting_event_create_properties_param import (
    ExternalCalendarMeetingEventCreatePropertiesParam as ExternalCalendarMeetingEventCreatePropertiesParam,
)
from .collection_response_with_total_external_link_metadata_forward_paging import (
    CollectionResponseWithTotalExternalLinkMetadataForwardPaging as CollectionResponseWithTotalExternalLinkMetadataForwardPaging,
)
